# Generated by Django 5.1.3 on 2025-02-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('calorias', models.PositiveIntegerField(default=0)),
                ('proteinas', models.PositiveIntegerField(default=0)),
                ('fibra', models.PositiveIntegerField(default=0)),
                ('carbohidratos', models.PositiveIntegerField(default=0)),
                ('grasas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('calorias', models.PositiveIntegerField(default=0)),
                ('proteinas', models.PositiveIntegerField(default=0)),
                ('fibra', models.PositiveIntegerField(default=0)),
                ('carbohidratos', models.PositiveIntegerField(default=0)),
                ('grasas', models.PositiveIntegerField(default=0)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='api.receta')),
            ],
        ),
    ]
