# Generated by Django 5.1.3 on 2025-02-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='carbohidratos',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='fibra',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='grasas',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='proteinas',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='receta',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receta_nombre',
            field=models.CharField(default='desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='carbohidratos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fibra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='grasas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
