# Generated by Django 5.1.3 on 2025-02-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ingrediente_calorias_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingrediente',
            table='api_ingredientes',
        ),
    ]
